#!/usr/bin/env php
<?php

function permissions($dir)
{
	umask(0000);
	if (!is_dir($dir)) {
		mkdir($dir, 0777, TRUE);

	} else {
		chmod($dir, 0777);
	}
}

permissions(__DIR__ . '/app/log');
permissions(__DIR__ . '/app/temp/cache');

system('vendor/vendors install');
system('rm ' . escapeshellarg(__FILE__));
